local config = require("grok.config")

describe("grok.config", function()
  before_each(function()
    config.reset()
  end)

  it("applies defaults", function()
    config.setup({})
    local c = config.get()
    assert.are.same({ "grok" }, c.tui_cmd)
    assert.are.equal("review", c.permission_mode)
    assert.are.equal("right", c.sidebar.position)
    assert.are.equal(0.36, c.sidebar.width)
    assert.is_true(c.diff_review)
    assert.is_true(c.nav_keys)
    assert.is_true(c.auto_reload)
    assert.are.equal(240, c.review_timeout)
  end)

  it("rejects invalid permission_mode", function()
    assert.has_error(function()
      config.setup({ permission_mode = "yolo" })
    end)
  end)

  it("merges partial sidebar opts", function()
    config.setup({ sidebar = { width = 0.4 } })
    local c = config.get()
    assert.are.equal(0.4, c.sidebar.width)
    assert.are.equal("right", c.sidebar.position)
  end)
end)
