local config = require("grok.config")
local render = require("grok.ui.render")

describe("render", function()
  before_each(function()
    config.reset()
    config.setup({})
  end)

  it("formats tool line", function()
    local line = render.format_tool({ title = "grep", status = "in_progress", kind = "search" })
    assert.truthy(line:find("grep"))
    assert.truthy(line:find("in_progress") or line:find("…") or line:find("running"))
    assert.truthy(line:find("▸") or line:find("⚙") or line:find("tool") or line:find("grep"))
  end)

  it("formats completed tool without running marker", function()
    local line = render.format_tool({ title = "read", status = "completed", kind = "read" })
    assert.truthy(line:find("read"))
    assert.truthy(line:find("✓") or line:find("completed"))
    assert.is_nil(line:find("in_progress"))
  end)

  it("formats user / agent / thought / permission prefixes", function()
    assert.truthy(render.format_user("hi"):find("You"))
    assert.truthy(render.format_agent("ok"):find("Grok"))
    assert.truthy(render.format_thought("hmm"):find("thought"))
    assert.truthy(
      render.format_permission("allow?"):find("permission") or render.format_permission("allow?"):find("%?")
    )
  end)

  it("hides thoughts when configured", function()
    config.setup({ thoughts = "hidden" })
    assert.is_false(render.should_show_thoughts())
  end)

  it("shows thoughts when collapsed or expanded", function()
    config.setup({ thoughts = "collapsed" })
    assert.is_true(render.should_show_thoughts())
    config.setup({ thoughts = "expanded" })
    assert.is_true(render.should_show_thoughts())
  end)

  it("splits multiline text into lines", function()
    local lines = render.split_lines("a\nb\nc")
    assert.are.same({ "a", "b", "c" }, lines)
  end)

  it("append_user / append_agent_chunk write prefixed buffer lines", function()
    local buf = vim.api.nvim_create_buf(false, true)
    render.clear(buf)
    render.append_user(buf, "hello")
    render.append_agent_chunk(buf, "world")
    render.append_agent_chunk(buf, " more")
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    local joined = table.concat(lines, "\n")
    assert.truthy(joined:find("You"))
    assert.truthy(joined:find("hello"))
    assert.truthy(joined:find("Grok"))
    assert.truthy(joined:find("world more") or (joined:find("world") and joined:find("more")))
    vim.api.nvim_buf_delete(buf, { force = true })
  end)

  it("skips thought chunks when hidden", function()
    config.setup({ thoughts = "hidden" })
    local buf = vim.api.nvim_create_buf(false, true)
    render.clear(buf)
    render.append_thought_chunk(buf, "secret")
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    local joined = table.concat(lines, "\n")
    assert.is_nil(joined:find("secret"))
    vim.api.nvim_buf_delete(buf, { force = true })
  end)

  it("upserts tool by id", function()
    local buf = vim.api.nvim_create_buf(false, true)
    render.clear(buf)
    render.upsert_tool(buf, "t1", { title = "grep", status = "in_progress", kind = "search" })
    render.upsert_tool(buf, "t1", { title = "grep", status = "completed", kind = "search" })
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    local tool_lines = 0
    for _, l in ipairs(lines) do
      if l:find("grep") then
        tool_lines = tool_lines + 1
        assert.truthy(l:find("✓") or l:find("completed"))
        assert.is_nil(l:find("in_progress"))
      end
    end
    assert.are.equal(1, tool_lines)
    vim.api.nvim_buf_delete(buf, { force = true })
  end)

  it("set_status updates chrome status text", function()
    local buf = vim.api.nvim_create_buf(false, true)
    render.clear(buf)
    render.set_status(buf, "review · idle")
    assert.truthy(render.get_status(buf):find("idle"))
    render.append_user(buf, "hi")
    render.set_status(buf, "auto · busy")
    assert.truthy(render.get_status(buf):find("busy"))
    assert.is_nil(render.get_status(buf):find("idle"))
    vim.api.nvim_buf_delete(buf, { force = true })
  end)

  it("show_welcome draws a branded empty state", function()
    local buf = vim.api.nvim_create_buf(false, true)
    render.show_welcome(buf, { mode = "review", model = "grok-4.5", cwd = "/tmp/proj" })
    local joined = table.concat(vim.api.nvim_buf_get_lines(buf, 0, -1, false), "\n")
    assert.truthy(joined:find("Grok Build"))
    assert.truthy(joined:find("review"))
    assert.truthy(joined:find("grok%-4%.5") or joined:find("grok-4.5"))
    vim.api.nvim_buf_delete(buf, { force = true })
  end)
end)
